"use client";
import {useMemo,useState} from "react";
import {Search,ShoppingBag,Menu,Heart,MapPin,Truck,CreditCard,Headphones,ShieldCheck,ArrowRight,ChevronRight,Star,X,Check} from "lucide-react";
const A="/needle/";
const items=[
 {id:1,n:"Sofá Bélgica Retrátil",m:"2,30 m • 4 lugares",p:3290,o:3990,c:"Sofás",i:"2026-07-15_10-45-00_Daz4Vu3uDvA.jpg",t:"Mais vendido"},
 {id:2,n:"Sofá Paris",m:"2,20 m • Retrátil",p:2890,o:3490,c:"Sofás",i:"2026-07-08_10-51-01_Dah3fBpuSmL.jpg",t:"Lançamento"},
 {id:3,n:"Poltrona Linêo",m:"80 cm • Linho premium",p:1290,o:1590,c:"Poltronas",i:"2026-06-12_16-54-14_DZfka0AEdND_3.jpg",t:"Pronta entrega"},
 {id:4,n:"Home Verona",m:"2,85 m • LED integrado",p:2890,o:3290,c:"Sala",i:"2025-12-07_21-33-41_DR-jv2IEqre.jpg",t:"Oferta"},
 {id:5,n:"Sofá Áustria",m:"2,30 m • Retrátil",p:3090,o:3690,c:"Sofás",i:"2026-07-03_11-05-33_DaVBIQUuuQ2.jpg",t:"Exclusivo"},
 {id:6,n:"Mesa Organic",m:"6 lugares • Madeira",p:2490,o:2990,c:"Mesas",i:"2026-06-23_11-43-09_DZ7VgBmRyEQ.jpg",t:"Novo"}];
const br=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Home(){const[q,setQ]=useState("");const[cat,setCat]=useState("Todos");const[cart,setCart]=useState<number[]>([]);const[favs,setFavs]=useState<number[]>([]);const[open,setOpen]=useState(false);const[menu,setMenu]=useState(false);const[step,setStep]=useState(0);const[done,setDone]=useState(false);const shown=useMemo(()=>items.filter(x=>(cat==="Todos"||x.c===cat)&&x.n.toLowerCase().includes(q.toLowerCase())),[q,cat]);const total=cart.reduce((a,id)=>a+(items.find(x=>x.id===id)?.p||0),0);const wa=(s:string)=>`https://wa.me/5521970496901?text=${encodeURIComponent(s)}`;return <main>
 <div className="top"><div>✦ Entrega em todo o Rio de Janeiro　　✦ Parcele em até 12x　　✦ Há mais de 10 anos transformando lares　　✦ Atendimento personalizado pelo WhatsApp</div></div>
 <header><div className="head wrap"><button className="hamb" onClick={()=>setMenu(!menu)}><Menu/></button><img className="logo" src={A+"needle_moveis_2026-05-31_14-16-58_UTC_profile_pic.jpg"}/><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="O que você procura para sua casa?"/></label><a className="location" href="#loja"><MapPin/><span>Nossa loja<br/><b>Taquara, RJ</b></span></a><button className="bag" onClick={()=>setOpen(true)}><ShoppingBag/>{cart.length>0&&<i>{cart.length}</i>}</button></div><nav className={menu?"show":""}>{["Sofás","Colchões","Camas e Box","Mesas","Poltronas","Pronta entrega","Ofertas","Ambientes"].map(x=><a href="#produtos" onClick={()=>{setCat(x);setMenu(false)}}>{x}</a>)}</nav></header>
 <section className="hero"><img src={A+"2026-08-20_11-25-15_DcQpPxJu3vh.jpg"}/><div className="shade"/><div className="heroCopy wrap"><em>CONHEÇA A NOVA NEEDLE</em><h1>Seu novo lar<br/>começa aqui.</h1><p>Sofás e móveis escolhidos para transformar conforto em parte da sua rotina.</p><div><a className="btn white" href="#produtos">Explorar produtos <ArrowRight/></a><a className="btn outline" href={wa("Olá! Quero ajuda para escolher móveis para minha casa.")}>Falar com especialista</a></div><small><Truck/> Entrega em todo o Rio de Janeiro</small></div></section>
 <section className="section wrap"><Title over="COMPRE POR CATEGORIA" title="Encontre o que combina com você"/><div className="cats">{[["Sofás","2026-08-19_11-44-44_DcOG-gOuBHY.jpg"],["Poltronas","2026-06-12_16-54-14_DZfka0AEdND_3.jpg"],["Mesas","2026-06-23_11-43-09_DZ7VgBmRyEQ.jpg"],["Sala","2025-12-07_21-33-41_DR-jv2IEqre.jpg"],["Pronta entrega","2026-07-20_11-02-10_DbAyRklOMss.jpg"]].map(([n,i])=><button onClick={()=>{setCat(n);document.querySelector("#produtos")?.scrollIntoView()}}><img src={A+i}/><span>{n}<ChevronRight/></span></button>)}</div></section>
 <section className="benefits"><div className="wrap benefitsGrid">{[[Truck,"Entrega em todo o RJ","Cuidado e segurança"],[CreditCard,"Até 12x no cartão","Condições especiais"],[Headphones,"Atendimento próximo","Especialistas para ajudar"],[ShieldCheck,"10 anos de confiança","Qualidade para sua casa"]].map(([I,t,d]:any)=><div><I/><span><b>{t}</b><small>{d}</small></span></div>)}</div></section>
 <section id="produtos" className="section wrap"><div className="titleRow"><Title over="CURADORIA NEEDLE" title="Destaques para transformar seu lar"/><div className="filters">{["Todos","Sofás","Poltronas","Mesas"].map(x=><button className={cat===x?"on":""} onClick={()=>setCat(x)}>{x}</button>)}</div></div><div className="grid">{shown.map(x=><article><div className="photo"><span>{x.t}</span><button className={favs.includes(x.id)?"liked":""} onClick={()=>setFavs(v=>v.includes(x.id)?v.filter(a=>a!==x.id):[...v,x.id])}><Heart fill={favs.includes(x.id)?"currentColor":"none"}/></button><img src={A+x.i}/><a onClick={()=>{setCart(v=>[...v,x.id]);setOpen(true)}}>Adicionar ao carrinho</a></div><div className="info"><small className="stars"><Star fill="currentColor"/> 4.9　(38)</small><h3>{x.n}</h3><small>{x.m}</small><s>{br(x.o)}</s><strong>{br(x.p)}</strong><p>ou <b>{br(x.p*.95)} no PIX</b><br/>12x de {br(x.p/12)} sem juros</p><a href={wa(`Olá! Estou vendo o ${x.n}. Quero confirmar disponibilidade e prazo de entrega.`)}>Comprar pelo WhatsApp</a></div></article>)}</div>{shown.length===0&&<p className="empty">Nenhum produto encontrado. Tente outra busca.</p>}</section>
 <section className="editorial wrap"><div><em>ESCOLHA PELO SEU MOMENTO</em><h2>Como você quer transformar a sua casa?</h2><p>Encontre uma seleção criada para o seu espaço, sua rotina e seu estilo.</p>{["Quero renovar minha sala","Quero dormir melhor","Quero uma sala de jantar nova","Preciso aproveitar melhor meu espaço"].map((x,i)=><a href="#produtos"><small>0{i+1}</small>{x}<ArrowRight/></a>)}</div><img src={A+"2026-08-09_11-54-49_Db0YJzHOe_F.jpg"}/></section>
 <section className="quiz"><div className="wrap quizGrid"><div><em>CONSULTORIA EXPRESS</em><h2>Encontre seu sofá ideal em menos de 1 minuto.</h2><p>Responda algumas perguntas e receba uma recomendação personalizada.</p></div><div className="quizCard">{!done?<><div className="progress"><i style={{width:`${(step+1)*25}%`}}/></div><small>PERGUNTA {step+1} DE 4</small><h3>{["Quantas pessoas usarão o sofá?","Qual a largura disponível?","Qual modelo você prefere?","Qual sua faixa de investimento?"][step]}</h3>{[["Até 2 pessoas","3 pessoas","4 ou mais"],["Até 1,80 m","1,80 m a 2,30 m","Acima de 2,30 m"],["Fixo","Retrátil","Retrátil e reclinável"],["Até R$ 2.500","R$ 2.500 a R$ 4.000","Acima de R$ 4.000"]][step].map(a=><button onClick={()=>step<3?setStep(step+1):setDone(true)}>{a}<ChevronRight/></button>)}</>:<div className="result"><i><Check/></i><small>ENCONTRAMOS UMA COMBINAÇÃO</small><h3>O Sofá Bélgica combina com você.</h3><p>Confortável, retrátil e com excelente aproveitamento de espaço.</p><a className="btn orange" href={wa("Olá! Fiz o quiz e recebi a recomendação do Sofá Bélgica.")}>Receber recomendação</a></div>}</div></div></section>
 <section className="section wrap"><Title over="AMBIENTES QUE INSPIRAM" title="Ideias para viver melhor"/><div className="mosaic"><figure><img src={A+"2026-07-02_11-06-38_DaScbLvulw1.jpg"}/><b>Sala de estar</b></figure><figure><img src={A+"2025-12-07_21-33-41_DR-jv2IEqre.jpg"}/><b>Home & TV</b></figure><figure><img src={A+"2026-06-12_16-54-14_DZfka0AEdND_2.jpg"}/><b>Cantinho de leitura</b></figure></div></section>
 <section id="loja" className="about"><img src={A+"2026-08-07_11-37-53_DbvMoskuhXE.jpg"}/><div><em>NOSSA HISTÓRIA</em><h2>Há mais de uma década transformando casas em lares.</h2><p>A Needle nasceu no Rio de Janeiro para oferecer móveis que unem conforto, qualidade e personalidade. Visite uma de nossas unidades e receba um atendimento próximo para encontrar a escolha certa.</p><div className="nums"><b>+10 <small>anos de história</small></b><b>2 <small>lojas no Rio de Janeiro</small></b></div><div className="storeLinks"><a href="https://maps.app.goo.gl/8N9CNkRVBzEzdZLf9" target="_blank" rel="noreferrer"><MapPin/><span><small>COMO CHEGAR</small>Unidade Taquara</span><ArrowRight/></a><a href="https://maps.app.goo.gl/qWcEirBd3XnkySdS9" target="_blank" rel="noreferrer"><MapPin/><span><small>COMO CHEGAR</small>Unidade Bangu</span><ArrowRight/></a></div></div></section>
 <section className="section wrap"><Title over="@NEEDLE_MOVEIS" title="Inspire-se com a gente"/><div className="insta">{["2026-06-22_11-22-07_DZ4uL3TuoGo.jpg","2026-07-03_11-05-33_DaVBIQUuuQ2.jpg","2026-07-08_10-51-01_Dah3fBpuSmL.jpg","2026-07-15_10-45-00_Daz4Vu3uDvA.jpg","2026-07-20_11-02-10_DbAyRklOMss.jpg"].map(i=><img src={A+i}/>)}</div></section>
 <section className="news"><div><em>CLUBE NEEDLE</em><h2>Novidades para deixar sua casa ainda mais sua.</h2></div><form onSubmit={e=>e.preventDefault()}><input placeholder="Seu nome"/><input placeholder="WhatsApp ou e-mail"/><button>Quero participar <ArrowRight/></button></form></section>
 <footer><div className="wrap foot"><div><img src={A+"needle_moveis_2026-05-31_14-16-58_UTC_profile_pic.jpg"}/><p>Conforto e design para transformar o seu lar.</p></div><div><b>Categorias</b><a>Sofás</a><a>Poltronas</a><a>Mesas de jantar</a><a>Pronta entrega</a></div><div><b>Atendimento</b><a>Entrega e montagem</a><a>Trocas e devoluções</a><a>Política de privacidade</a><a>Meus pedidos</a></div><div><b>Nossas lojas</b><a href="https://maps.app.goo.gl/8N9CNkRVBzEzdZLf9" target="_blank" rel="noreferrer">Unidade Taquara • Ver no mapa</a><a href="https://maps.app.goo.gl/qWcEirBd3XnkySdS9" target="_blank" rel="noreferrer">Unidade Bangu • Ver no mapa</a><a href={wa("Olá, Needle!")}>Falar pelo WhatsApp</a></div></div><div className="copy wrap">© 2026 Needle Móveis & Colchões.<span>Compra segura • Ambiente protegido</span></div></footer>
 <a className="float" href={wa("Olá! Vim pelo site e gostaria de atendimento.")}>WA</a>
 {open&&<div className="overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><div className="asideHead"><h3>Seu carrinho ({cart.length})</h3><button onClick={()=>setOpen(false)}><X/></button></div><div className="cartList">{cart.length===0?<div className="empty"><ShoppingBag/><h3>Seu carrinho está vazio</h3><button onClick={()=>setOpen(false)}>Explorar produtos</button></div>:cart.map((id,n)=>{const x=items.find(a=>a.id===id)!;return <div className="cartItem"><img src={A+x.i}/><div><b>{x.n}</b><small>{x.m}</small><strong>{br(x.p)}</strong><button onClick={()=>setCart(v=>v.filter((_,j)=>j!==n))}>Remover</button></div></div>})}</div>{cart.length>0&&<div className="total"><p>Subtotal <b>{br(total)}</b></p><small>Frete calculado na próxima etapa</small><button>Finalizar compra</button><a href={wa(`Olá! Quero finalizar meu pedido no valor de ${br(total)}.`)}>Finalizar pelo WhatsApp</a></div>}</aside></div>}
 </main>}
function Title({over,title}:{over:string,title:string}){return <div className="title"><em>{over}</em><h2>{title}</h2></div>}
