"use client";
import {useEffect,useMemo,useState} from "react";
import {Search,ShoppingBag,Menu,Heart,MapPin,Truck,CreditCard,Headphones,ShieldCheck,ArrowRight,ChevronRight,Star,X,Check,MessageCircle} from "lucide-react";
const A="/needle/";
const items=[
 {id:1,n:"Sofá Bélgica Retrátil",m:"2,30 m • 4 lugares",p:3290,o:3990,c:"Sofás",i:"2026-07-15_10-45-00_Daz4Vu3uDvA.jpg",t:"Mais vendido"},
 {id:2,n:"Sofá Paris",m:"2,20 m • Retrátil",p:2890,o:3490,c:"Sofás",i:"2026-07-08_10-51-01_Dah3fBpuSmL.jpg",t:"Lançamento"},
 {id:3,n:"Poltrona Linêo",m:"80 cm • Linho premium",p:1290,o:1590,c:"Poltronas",i:"2026-06-12_16-54-14_DZfka0AEdND_3.jpg",t:"Pronta entrega"},
 {id:4,n:"Home Verona",m:"2,85 m • LED integrado",p:2890,o:3290,c:"Sala",i:"2025-12-07_21-33-41_DR-jv2IEqre.jpg",t:"Oferta"},
 {id:5,n:"Sofá Áustria",m:"2,30 m • Retrátil",p:3090,o:3690,c:"Sofás",i:"2026-07-03_11-05-33_DaVBIQUuuQ2.jpg",t:"Exclusivo"},
 {id:6,n:"Mesa Organic",m:"6 lugares • Madeira",p:2490,o:2990,c:"Mesas",i:"2026-06-23_11-43-09_DZ7VgBmRyEQ.jpg",t:"Novo"}];
const br=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const heroSlides=["2026-08-19_11-44-44_DcOG-gOuBHY.jpg","2026-07-08_10-51-01_Dah3fBpuSmL.jpg","2026-07-03_11-05-33_DaVBIQUuuQ2.jpg","2026-07-02_11-06-38_DaScbLvulw1.jpg"];
const navGroups=[
 {name:"Sofás",links:["Retráteis","Reclináveis","Sofás de 2 lugares","Sofás de 3 e 4 lugares"],image:"2026-08-19_11-44-44_DcOG-gOuBHY.jpg"},
 {name:"Sala",links:["Homes e painéis","Racks","Mesas de centro","Ambientes completos"],image:"2025-12-07_21-33-41_DR-jv2IEqre.jpg"},
 {name:"Mesas",links:["Mesas de jantar","Mesas para 4 lugares","Mesas para 6 lugares","Cadeiras"],image:"2026-06-23_11-43-09_DZ7VgBmRyEQ.jpg"},
 {name:"Poltronas",links:["Poltronas decorativas","Poltronas para leitura","Poltronas em linho","Lançamentos"],image:"2026-06-12_16-54-14_DZfka0AEdND_3.jpg"},
 {name:"Pronta entrega",links:["Sofás disponíveis","Poltronas disponíveis","Ofertas da semana","Consultar estoque"],image:"2026-07-20_11-02-10_DbAyRklOMss.jpg"},
 {name:"Ofertas",links:["Mais vendidos","Últimas unidades","Condições especiais","Comprar pelo WhatsApp"],image:"2026-07-08_10-51-01_Dah3fBpuSmL.jpg"}
];
export default function Home(){const[q,setQ]=useState("");const[cat,setCat]=useState("Todos");const[cart,setCart]=useState<number[]>([]);const[favs,setFavs]=useState<number[]>([]);const[open,setOpen]=useState(false);const[checkout,setCheckout]=useState(false);const[orderDone,setOrderDone]=useState(false);const[menu,setMenu]=useState(false);const[step,setStep]=useState(0);const[done,setDone]=useState(false);const[hero,setHero]=useState(0);const[name,setName]=useState("");const[contact,setContact]=useState("");const shown=useMemo(()=>items.filter(x=>{const category=cat==="Todos"||x.c===cat||(cat==="Pronta entrega"&&x.t==="Pronta entrega")||(cat==="Ofertas"&&x.t==="Oferta");return category&&x.n.toLowerCase().includes(q.toLowerCase())}),[q,cat]);const total=cart.reduce((a,id)=>a+(items.find(x=>x.id===id)?.p||0),0);const wa=(s:string)=>`https://wa.me/5521970496901?text=${encodeURIComponent(s)}`;useEffect(()=>{const timer=setInterval(()=>setHero(v=>(v+1)%heroSlides.length),5000);return()=>clearInterval(timer)},[]);const choose=(category:string)=>{setCat(category);setQ("");setMenu(false)};return <main id="top">
 <div className="top"><div className="ticker"><span>✦ Entrega em todo o Rio de Janeiro　　✦ Parcele em até 12x　　✦ Há mais de 10 anos transformando lares　　✦ Atendimento personalizado pelo WhatsApp　　</span><span aria-hidden="true">✦ Entrega em todo o Rio de Janeiro　　✦ Parcele em até 12x　　✦ Há mais de 10 anos transformando lares　　✦ Atendimento personalizado pelo WhatsApp　　</span></div></div>
 <header><div className="head wrap"><button className="hamb" aria-label="Abrir menu" onClick={()=>setMenu(!menu)}><Menu/></button><a className="logoLink" href="#top" aria-label="Needle Móveis — voltar ao topo"><img className="logo" src={A+"needle_moveis_2026-05-31_14-16-58_UTC_profile_pic.jpg"} alt="Needle Móveis e Colchões"/></a><label className="search"><Search/><span className="srOnly">Buscar produtos</span><input value={q} onChange={e=>{setQ(e.target.value);setCat("Todos")}} placeholder="O que você procura para sua casa?"/></label><a className="location" href="#loja"><MapPin/><span>Nossas lojas<br/><b>Taquara e Bangu</b></span></a><button className="bag" aria-label={`Abrir carrinho com ${cart.length} itens`} onClick={()=>setOpen(true)}><ShoppingBag/>{cart.length>0&&<i>{cart.length}</i>}</button></div><nav className={menu?"show":""}>{navGroups.map(group=><div className="navItem" key={group.name}><a href="#produtos" onClick={()=>choose(group.name)}>{group.name}</a><div className="mega"><div><small>COMPRE POR CATEGORIA</small><b>{group.name}</b>{group.links.map(link=><a key={link} href="#produtos" onClick={()=>choose(group.name)}>{link}<ArrowRight/></a>)}</div><figure><img src={A+group.image} alt={`Destaque de ${group.name}`}/><figcaption>Conheça os destaques <ArrowRight/></figcaption></figure></div></div>)}<a href="#ambientes" onClick={()=>setMenu(false)}>Ambientes</a><a href="#loja" onClick={()=>setMenu(false)}>Lojas</a></nav></header>
 <section className="hero">{heroSlides.map((image,index)=><img key={image} className={index===hero?"active":""} src={A+image} alt={index===0?"Sofá retrátil em ambiente decorado":"Móveis Needle em ambiente decorado"} fetchPriority={index===0?"high":"auto"}/>) }<div className="shade"/><div className="heroCopy wrap"><em>CONHEÇA A NOVA NEEDLE</em><h1>Seu novo lar<br/>começa aqui.</h1><p>Sofás e móveis escolhidos para transformar conforto em parte da sua rotina.</p><div><a className="btn white" href="#produtos">Explorar produtos <ArrowRight/></a><a className="btn outline" href={wa("Olá! Quero ajuda para escolher móveis para minha casa.")}>Falar com especialista</a></div><small><Truck/> Entrega em todo o Rio de Janeiro</small></div><div className="heroDots" aria-label="Escolher banner">{heroSlides.map((_,index)=><button key={index} aria-label={`Mostrar banner ${index+1}`} className={index===hero?"on":""} onClick={()=>setHero(index)}/>)}</div></section>
 <section className="section wrap"><Title over="COMPRE POR CATEGORIA" title="Encontre o que combina com você"/><div className="cats">{[["Sofás","2026-08-19_11-44-44_DcOG-gOuBHY.jpg"],["Poltronas","2026-06-12_16-54-14_DZfka0AEdND_3.jpg"],["Mesas","2026-06-23_11-43-09_DZ7VgBmRyEQ.jpg"],["Sala","2025-12-07_21-33-41_DR-jv2IEqre.jpg"],["Pronta entrega","2026-07-20_11-02-10_DbAyRklOMss.jpg"]].map(([n,i])=><button key={n} onClick={()=>{choose(n);document.querySelector("#produtos")?.scrollIntoView()}}><img src={A+i} alt={`Categoria ${n}`} loading="lazy"/><span>{n}<ChevronRight/></span></button>)}</div></section>
 <section className="benefits"><div className="wrap benefitsGrid">{[[Truck,"Entrega em todo o RJ","Cuidado e segurança"],[CreditCard,"Até 12x no cartão","Condições especiais"],[Headphones,"Atendimento próximo","Especialistas para ajudar"],[ShieldCheck,"10 anos de confiança","Qualidade para sua casa"]].map(([I,t,d]:any)=><div><I/><span><b>{t}</b><small>{d}</small></span></div>)}</div></section>
 <section id="produtos" className="section wrap"><div className="titleRow"><Title over="CURADORIA NEEDLE" title="Destaques para transformar seu lar"/><div className="filters">{["Todos","Sofás","Sala","Poltronas","Mesas","Pronta entrega","Ofertas"].map(x=><button key={x} className={cat===x?"on":""} onClick={()=>choose(x)}>{x}</button>)}</div></div><div className="grid">{shown.map(x=><article key={x.id}><div className="photo"><span>{x.t}</span><button aria-label={`${favs.includes(x.id)?"Remover":"Adicionar"} ${x.n} dos favoritos`} className={favs.includes(x.id)?"liked":""} onClick={()=>setFavs(v=>v.includes(x.id)?v.filter(a=>a!==x.id):[...v,x.id])}><Heart fill={favs.includes(x.id)?"currentColor":"none"}/></button><img src={A+x.i} alt={x.n} loading="lazy"/></div><div className="info"><small className="stars"><Star fill="currentColor"/> Consulte avaliações</small><h3>{x.n}</h3><small>{x.m}</small><s>{br(x.o)}</s><strong>{br(x.p)}</strong><p>ou <b>{br(x.p*.95)} no PIX</b><br/>12x de {br(x.p/12)} sem juros</p><button className="buyCart" onClick={()=>{setCart(v=>[...v,x.id]);setCheckout(false);setOpen(true)}}>Adicionar ao carrinho</button></div></article>)}</div>{shown.length===0&&<p className="empty">Não encontramos esse item. <button onClick={()=>choose("Todos")}>Ver todos os produtos</button></p>}</section>
 <section className="editorial wrap"><div><em>ESCOLHA PELO SEU MOMENTO</em><h2>Como você quer transformar a sua casa?</h2><p>Encontre uma seleção criada para o seu espaço, sua rotina e seu estilo.</p>{["Quero renovar minha sala","Quero dormir melhor","Quero uma sala de jantar nova","Preciso aproveitar melhor meu espaço"].map((x,i)=><a href="#produtos"><small>0{i+1}</small>{x}<ArrowRight/></a>)}</div><img src={A+"2026-08-09_11-54-49_Db0YJzHOe_F.jpg"}/></section>
 <section className="quiz"><div className="wrap quizGrid"><div><em>CONSULTORIA EXPRESS</em><h2>Encontre seu sofá ideal em menos de 1 minuto.</h2><p>Responda algumas perguntas e receba uma recomendação personalizada.</p></div><div className="quizCard">{!done?<><div className="progress"><i style={{width:`${(step+1)*25}%`}}/></div><small>PERGUNTA {step+1} DE 4</small><h3>{["Quantas pessoas usarão o sofá?","Qual a largura disponível?","Qual modelo você prefere?","Qual sua faixa de investimento?"][step]}</h3>{[["Até 2 pessoas","3 pessoas","4 ou mais"],["Até 1,80 m","1,80 m a 2,30 m","Acima de 2,30 m"],["Fixo","Retrátil","Retrátil e reclinável"],["Até R$ 2.500","R$ 2.500 a R$ 4.000","Acima de R$ 4.000"]][step].map(a=><button onClick={()=>step<3?setStep(step+1):setDone(true)}>{a}<ChevronRight/></button>)}</>:<div className="result"><i><Check/></i><small>ENCONTRAMOS UMA COMBINAÇÃO</small><h3>O Sofá Bélgica combina com você.</h3><p>Confortável, retrátil e com excelente aproveitamento de espaço.</p><a className="btn orange" href={wa("Olá! Fiz o quiz e recebi a recomendação do Sofá Bélgica.")}>Receber recomendação</a></div>}</div></div></section>
 <section id="ambientes" className="section wrap"><Title over="AMBIENTES QUE INSPIRAM" title="Ideias para viver melhor"/><div className="mosaic"><figure><img src={A+"2026-07-02_11-06-38_DaScbLvulw1.jpg"} alt="Sala de estar com sofá retrátil" loading="lazy"/><b>Sala de estar</b></figure><figure><img src={A+"2025-12-07_21-33-41_DR-jv2IEqre.jpg"} alt="Painel para televisão" loading="lazy"/><b>Home & TV</b></figure><figure><img src={A+"2026-06-12_16-54-14_DZfka0AEdND_3.jpg"} alt="Poltrona para cantinho de leitura" loading="lazy"/><b>Cantinho de leitura</b></figure></div></section>
 <section id="loja" className="about"><img src={A+"2026-08-07_11-37-53_DbvMoskuhXE.jpg"}/><div><em>NOSSA HISTÓRIA</em><h2>Há mais de uma década transformando casas em lares.</h2><p>A Needle nasceu no Rio de Janeiro para oferecer móveis que unem conforto, qualidade e personalidade. Visite uma de nossas unidades e receba um atendimento próximo para encontrar a escolha certa.</p><div className="nums"><b>+10 <small>anos de história</small></b><b>2 <small>lojas no Rio de Janeiro</small></b></div><div className="storeLinks"><a href="https://maps.app.goo.gl/8N9CNkRVBzEzdZLf9" target="_blank" rel="noreferrer"><MapPin/><span><small>COMO CHEGAR</small>Unidade Taquara</span><ArrowRight/></a><a href="https://maps.app.goo.gl/qWcEirBd3XnkySdS9" target="_blank" rel="noreferrer"><MapPin/><span><small>COMO CHEGAR</small>Unidade Bangu</span><ArrowRight/></a></div></div></section>
 <section className="section wrap"><Title over="@NEEDLE_MOVEIS" title="Inspire-se com a gente"/><div className="insta">{["2026-06-22_11-22-07_DZ4uL3TuoGo.jpg","2026-07-03_11-05-33_DaVBIQUuuQ2.jpg","2026-07-08_10-51-01_Dah3fBpuSmL.jpg","2026-07-15_10-45-00_Daz4Vu3uDvA.jpg","2026-07-20_11-02-10_DbAyRklOMss.jpg"].map(i=><img src={A+i}/>)}</div></section>
 <section className="news"><div><em>CLUBE NEEDLE</em><h2>Novidades para deixar sua casa ainda mais sua.</h2></div><form onSubmit={e=>{e.preventDefault();if(!name.trim()||!contact.trim())return;window.open(wa(`Olá! Quero participar do Clube Needle. Meu nome é ${name} e meu contato é ${contact}.`),"_blank","noopener,noreferrer")}}><label><span className="srOnly">Seu nome</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome" required/></label><label><span className="srOnly">WhatsApp ou e-mail</span><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="WhatsApp ou e-mail" required/></label><button>Quero participar <ArrowRight/></button><small>Ao enviar, você será direcionado ao WhatsApp da loja.</small></form></section>
 <footer><div className="wrap foot"><div><img src={A+"needle_moveis_2026-05-31_14-16-58_UTC_profile_pic.jpg"} alt="Needle Móveis e Colchões"/><p>Conforto e design para transformar o seu lar.</p></div><div><b>Categorias</b><a href="#produtos" onClick={()=>choose("Sofás")}>Sofás</a><a href="#produtos" onClick={()=>choose("Poltronas")}>Poltronas</a><a href="#produtos" onClick={()=>choose("Mesas")}>Mesas de jantar</a><a href="#produtos" onClick={()=>choose("Pronta entrega")}>Pronta entrega</a></div><div><b>Atendimento</b><a href={wa("Olá! Quero informações sobre entrega e montagem.")}>Entrega e montagem</a><a href={wa("Olá! Quero informações sobre trocas e devoluções.")}>Trocas e devoluções</a><a href={wa("Olá! Preciso de ajuda com meu pedido.")}>Meus pedidos</a></div><div><b>Nossas lojas</b><a href="https://maps.app.goo.gl/8N9CNkRVBzEzdZLf9" target="_blank" rel="noreferrer">Unidade Taquara • Ver no mapa</a><a href="https://maps.app.goo.gl/qWcEirBd3XnkySdS9" target="_blank" rel="noreferrer">Unidade Bangu • Ver no mapa</a><a href={wa("Olá, Needle!")}>Falar pelo WhatsApp</a></div></div><div className="copy wrap">© 2026 Needle Móveis & Colchões.<span>Preços e disponibilidade sujeitos à confirmação.</span></div></footer>
 <a className="float" aria-label="Falar com a Needle pelo WhatsApp" href={wa("Olá! Vim pelo site e gostaria de atendimento.")}><MessageCircle/></a>
 {open&&<div className="overlay" onClick={()=>setOpen(false)}><aside aria-label="Carrinho de compras" onClick={e=>e.stopPropagation()}><div className="asideHead"><div>{checkout&&<button className="backCart" onClick={()=>setCheckout(false)}>← Voltar</button>}<h3>{checkout?"Finalizar compra":`Seu carrinho (${cart.length})`}</h3></div><button aria-label="Fechar carrinho" onClick={()=>setOpen(false)}><X/></button></div>{orderDone?<div className="orderDone"><i><Check/></i><h3>Pedido registrado!</h3><p>Esta é uma demonstração do checkout. A etapa de pagamento será liberada após a integração com o meio de pagamento da loja.</p><button onClick={()=>{setOrderDone(false);setCheckout(false);setCart([]);setOpen(false)}}>Continuar navegando</button></div>:checkout?<form className="checkoutForm" onSubmit={e=>{e.preventDefault();setOrderDone(true)}}><h4>Dados do cliente</h4><input required placeholder="Nome completo"/><input required type="email" placeholder="E-mail"/><input required inputMode="tel" placeholder="Telefone"/><h4>Endereço de entrega</h4><input required inputMode="numeric" placeholder="CEP"/><input required placeholder="Endereço e número"/><div><input required placeholder="Bairro"/><input required placeholder="Cidade" defaultValue="Rio de Janeiro"/></div><h4>Forma de pagamento</h4><label className="payOption"><input required type="radio" name="payment"/> PIX</label><label className="payOption"><input required type="radio" name="payment"/> Cartão de crédito</label><p className="checkoutTotal">Total <b>{br(total)}</b></p><button className="finishOrder">Finalizar pedido</button><small>Pagamento ainda em modo de demonstração.</small></form>:<><div className="cartList">{cart.length===0?<div className="empty"><ShoppingBag/><h3>Seu carrinho está vazio</h3><button onClick={()=>setOpen(false)}>Explorar produtos</button></div>:cart.map((id,n)=>{const x=items.find(a=>a.id===id)!;return <div className="cartItem" key={`${id}-${n}`}><img src={A+x.i} alt={x.n}/><div><b>{x.n}</b><small>{x.m}</small><strong>{br(x.p)}</strong><button onClick={()=>setCart(v=>v.filter((_,j)=>j!==n))}>Remover</button></div></div>})}</div>{cart.length>0&&<div className="total"><p>Subtotal <b>{br(total)}</b></p><small>Frete calculado no checkout.</small><button className="goCheckout" onClick={()=>setCheckout(true)}>Ir para o checkout</button></div>}</>}</aside></div>}
 </main>}
function Title({over,title}:{over:string,title:string}){return <div className="title"><em>{over}</em><h2>{title}</h2></div>}
